# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-29 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyze', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalystpic',
            name='pic',
            field=models.ImageField(upload_to=b'/Users/lus/sandbox/techinclusion/uploaded_pics/'),
        ),
    ]
